### ISSUE TITLE
Deployment Problem

### ISSUE THREAD

**Issue by cfespinoza** [P2Pvalue/pear2pear#1]
Hey people, I've tried to deploy the project in local environment but I found some problems with the tutorial.

The first one is in file ***.bowerrc***, it should look like this:
```json
{
  "directory": "app/bower_components",
}
instead of:
{
  "directory": "bower_components"
}
```

Another problem that I found when I've tried to launch the service with instruction ***npm start***. It didn't launch the service. I had to add some code lines in file ***package.json*** in scripts section. My local file looks like this:
```json
"scripts": {
    "postinstall": "node node_modules/protractor/bin/webdriver-manager update; bower install",

    "prestart": "npm install",
    
    "start": "http-server -a 0.0.0.0 -p 8000",

    "pretest": "npm install",

    "test": "grunt test"
}
```

**Comment by atd** [comment]
Hi @cfespinoza 

I am afraid that our README is outdated :grin: 

Packages are not installed in `app/bower_components` but are compiled in production or directly served in development.

For launching the service, just run `grunt serve`

**Comment by atd** [comment]
I am closing the issue.

Please, reopen if you find further problems
