### ISSUE TITLE
Project ids

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#19]
Project ids should be unique, not random

@pablojan , does SwellRT manage object ids?

If not, we should generate them from hash or other way

**Comment by atd** [comment]
Message ids would be useful as well, for chat scrolling to the bottom or unread messages

**Comment by pablojan** [comment]
Currently SwellRT doesn't provide an Id generator for objects stored in their data models. If it's necessary we could provide it (I think in a Id counter for the whole SwellRT model)

So far, you can rely on list's index if you are using lists, For maps, it makes sense the app to manage the keys.

**Comment by atd** [comment]
I think we can live with indexes and keys by now.

**Comment by atd** [comment]
Will fix with https://github.com/P2Pvalue/pear2pear/issues/34
