### ISSUE TITLE
Websockets not working correctly

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/pear2pear#20]
In deployed pear2pear: 
  When editing a pad, you can not see the edits from other browser tab with that pad open... also happens with chat messages, they do not appear.

In locally deployed pear2pear with swellrt:
  Chat and pad work as expected: text is updated and chat messages added

Please, @atd and @pablojan, can you confirm it is working in your local environment? can you give ideas about why it is happening?

My guesses:
  swellrt is not deployed in its last version in wave.p2pvalue.eu
  https is interfering somehow... did't wave/kune had problems with that?
  
:sad: It was so beautiful in my computer...

**Comment by atfornes** [comment]
Reopen #8 if not working in your other environments

**Comment by atd** [comment]
It happens to me in some cases.

I guess it is a matter of latency, but need more research

**Comment by atfornes** [comment]
I redeployed SwellRT and the problem looks solved !
However, the resolution is not because of the version of the code (same as previously deployed), but probably because of the SwellRT server restart.

We will check if this SwellRT server failures keeps happening or were something puntual.

**Comment by atd** [comment]
I wouldn't say the server restart failed.

It is happening to me again :sad:

2015-05-30 7:35 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
Issue reproduced:

1 Open the same pad in two browser tabs/windows
2 They keep working until one of the tabs receives a GET socket upgrade connection like the following:

Host: wave.p2pvalue.eu
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Sec-WebSocket-Version: 13
Origin: https://p.p2pvalue.eu
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: eZ67ut1wfYSy7AUyoXI1YQ==
Cookie: WSESSIONID=1um6s1yogtnmn1f6cxu2rx47il
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

**Comment by pablojan** [comment]
Mmmm, could it be a Wave's session conflict!

2015-06-01 12:15 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
Pablojan, it could be, since the user is the same in this stage of development. Anyway, it should not happend since a user could have two session opened (e.g. mobile and computer)

Should I open an issue in p2pvalue/swellrt for this?

**Comment by pablojan** [comment]
Did you tried with two different browsers and same user?
I suspect "Cookie: WSESSIONID=1um6s1yogtnmn1f6cxu2rx47il" could be shared
and make a mess...

2015-06-01 12:37 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
@pablojan, I have tested with two browsers, same user and keeps failing after the socket upgrade call.

Locally this not happens because the socket upgrade call is made only once, unlike when we connect to the deployed server where the socket upgrade connection is made once in a while.

**Comment by atd** [comment]
@pablojan I believe that after your work in SwellRT, we can close this issue, right?
