### ISSUE TITLE
Pad rich text edition integration

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/pear2pear#23]
Integrate the SwellRT rich text editor in pad.

See #14

**Comment by atd** [comment]
Waiting for https://github.com/P2Pvalue/swellrt/issues/26

**Comment by atd** [comment]
SwellRT already provides this functionality

https://github.com/P2Pvalue/swellrt/commit/c7ecdc6b7a9a6cc8e22410e4f94ee1d294565cf5

**Comment by atfornes** [comment]
I have a proposal for integration. Waiting for P2Pvalue/swellrt#27
