### ISSUE TITLE
Reduce rich text pad editor "text space"

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/pear2pear#28]
after 5488167 the pad space between lines is huge (100%).

Modify sass/pad.sass to fix this style issue.

@atd, can you please have a look on this? I could not solve it and I know you are more experienced in this. Thanks!!! :)

**Comment by atd** [comment]
Fixed via 0b5799d48f216c3ce23b9e5df1a8cef66b022498 and 07d5dd1b5d6f01fd07aaf48442611598e0bc9440
