### ISSUE TITLE
Temporarily disable websockets

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#30]

**Comment by atd** [comment]
@pablojan I guess you are working on this, so maybe this issue became obsolete?

**Comment by pablojan** [comment]
Yes, I have deployed a patch for both websockets and long-polling, so you
can ignore this issue

2015-07-08 12:32 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Ok, we can reopen it if we need it
