### ISSUE TITLE
Communities support

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#33]

**Comment by atd** [comment]
@atfornes  Was communities branch merged to master? I can see the functionality but cannot see the merge commit and github does not show it as merged

**Comment by atfornes** [comment]
Merged by f9bcee9edabcaa772f58c3d7a5ea839626fbdb02

I have pushed to communities branch a change that I only had locally in that branch, probably this fix the merge visualization: https://github.com/P2Pvalue/pear2pear/network

**Comment by atd** [comment]
Cool!

I'm deleting the branch then
