### ISSUE TITLE
Cannot delete weird trailing characters in pad

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#42]
While editing the pad, weird characters appeared and the end of the edition: `,í`. I cannot get rid of them. When I put the cursor at the end and try to delete them, the cursor jumps backwards and deletes the characters before them

![image](https://cloud.githubusercontent.com/assets/26228/8565956/a7179e14-255a-11e5-9b32-aa83ebccdb94.png)

**Comment by pablojan** [comment]
Fixed in ??? version
