### ISSUE TITLE
Pad does not work on Ubuntu phone neither in iPad Chrome

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#43]
Clicking the pad editor does nothing in those devices.

@pablojan can you please confirm the bug in your iPad?

**Comment by pablojan** [comment]
I can't reproduce it. IPad OSX 7.1.1 - Chrome 43.0.2357.61

**Comment by pablojan** [comment]
Issues with IPad OSX 7.1.1- Safari -> accepting 3rd party cookies must be enabled on Safari preferences. It still took quite time to load but it works
