### ISSUE TITLE
@undefined is shown in chat name

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#55]
When entering the chat, you can see messages from other people as `nick@undefined`

@atfornes maybe it was a good idea to store just the nick :wink:

**Comment by atfornes** [comment]
@atd, I believe the complete user identifier should be stored in the wave as the author of a chat messages to support federation. However, you can:
 - store in the cookie only the user id without domain
 - present in chat messages view only the user id without domain (as it is done now to show project promoter in project list view)

**Comment by atd** [comment]
Ok, I see your point

We will see in the future how to show people from other servers. In the mean time, it is ok if we show just the nick without the domain

**Comment by atd** [comment]
Fixed in https://github.com/P2Pvalue/pear2pear/commit/df1866dfd63b33762c59b91ec50c8c282203b0df
