### ISSUE TITLE
Pad show multiple divs with the placeholder

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#56]
After typing something in the pad, all the divs have the placeholder, increasing the document size unnecessarily

**Comment by atfornes** [comment]
fixed by #af4bd6c

@atd, can you confirm that is fixed?

**Comment by atd** [comment]
Sorry but it does not.

New divs do not have the placeholder, but when you reload the pad, all the divs have it

![image](https://cloud.githubusercontent.com/assets/26228/9325158/a41eef7c-4590-11e5-9367-9bd0272ea84b.png)
