### ISSUE TITLE
Other users can see new projects, which should be shared by link only

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#57]
1. Enter as user one
2. Create community and project
3. Go to frontpage and enter as user two
4. Go to empty community
5. Click in 'link' project

We should make a test to ensure we are not leaking information in this way

**Comment by atfornes** [comment]
I believe this was due to a wrong session initialization solved at 6abdbbd, that set the usernames to undefined@domain

**Comment by atd** [comment]
We need some tests for this

2015-08-17 18:10 GMT+02:00 atfornes <notifications@github.com>:
