### ISSUE TITLE
Show tooltip in avatars or more info about the participant.

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/pear2pear#59]
Now only the participant name's first letter is shown, but I can't event know the name.

**Comment by atd** [comment]
I agree.

Note that we cannot use hover tooltips, as they are useless in touch devices

**Comment by pablojan** [comment]
As long as we can't user hover tooltips, what do you suggest? could it be a
simple profile page showing just the user nick name?

2015-09-18 9:04 GMT+02:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
Showing names right now
