### ISSUE TITLE
Cannot use pad in Android 5

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#65]
When clicking in the pad, screen is blurred, see pic

![screenshot_2015-09-21-10-11-05](https://cloud.githubusercontent.com/assets/26228/9987598/843c8920-6049-11e5-9f7a-acfeed00c074.png)

**Comment by pablojan** [comment]
After writting 2 chars, cursor starts flickering

**Comment by pablojan** [comment]
See https://github.com/P2Pvalue/swellrt/issues/42
