### ISSUE TITLE
Notification icons are not shown

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#95]
In project list, pad editions and messages count icons are not activated by updates

**Comment by atfornes** [comment]
I will fix this, Also I would add more detail counting when an user have seen each tab and not just the project to have more granularity.

**Comment by atd** [comment]
But please @atfornes, try to make smaller and more frequent commits 

I mean, you don't need to wait until notifications are fully implemented to fix this bug

:wink:
